# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: NEXIAL_HOME
    displayName: Nexial Location
    type: string
    default: C:\projects\nexial-core
  - name: SCRIPT_NAME
    displayName: Target Nexial script
    type: string
    default: macroTest
    values:
      - complex-script
      - macro1Test
      - macroTest2
      - macroTest
      - wrongTotalStepTally

trigger: none

pool: Default
#   vmImage: ubuntu-latest

steps:
  - script: |
      set NEXIAL_HOME=${{ parameters.NEXIAL_HOME }}
      set PROJECT_HOME=$(Build.Repository.LocalPath)
      set SCRIPT_NAME=${{ parameters.SCRIPT_NAME }}
      set SCRIPT_FILE=%PROJECT_HOME%\artifact\script\%SCRIPT_NAME%.xlsx
      set JAVA_OPT=-Dnexial.openResult=false
      set NEXIAL_OUTPUT=
      cd /d %NEXIAL_HOME%
      cd bin
      nexial.cmd -script %SCRIPT_FILE%
      echo '$(System.DefaultWorkingDirectory)'
      echo.
      displayName: Run wrongTotalStep POC script
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '\\**\\*.trx'
      searchFolder: '$(System.DefaultWorkingDirectory)\\output\\'
      failTaskOnFailedTests: true